import { addDays, iso, startOfWeek } from '../lib/date';
import type {
  Artigo,
  Categoria,
  DataState,
  Grupo,
  Marcacao,
  Orcamento,
  Parceiro,
  SubGrupo,
} from './types';

/**
 * Demonstration dataset. Dates are generated relative to `today` so the agenda
 * always has content in the current week, whenever the app is opened.
 *
 * Replace this module with API calls when the backend lands — nothing outside
 * `createSeedData` depends on the values being static.
 */
export function createSeedData(today: Date): DataState {
  /** ISO date, `n` days after the Monday of the current week. */
  const d = (n: number) => iso(addDays(startOfWeek(today), n));

  const subgrupos: SubGrupo[] = [
    { id: 's1', nome: 'Cimentos' },
    { id: 's2', nome: 'Areias e britas' },
    { id: 's3', nome: 'Tubagem PVC' },
    { id: 's4', nome: 'Torneiras' },
    { id: 's5', nome: 'Tinta interior' },
    { id: 's6', nome: 'Tinta exterior' },
    { id: 's7', nome: 'Azulejo' },
    { id: 's8', nome: 'Pavimento' },
    { id: 's9', nome: 'Cabo elétrico' },
    { id: 's10', nome: 'Quadros elétricos' },
    { id: 's11', nome: 'Placas de gesso' },
    { id: 's12', nome: 'Perfis metálicos' },
  ];

  const grupos: Grupo[] = [
    { id: 'g1', nome: 'Alvenaria', subgrupoIds: ['s1', 's2'] },
    { id: 'g2', nome: 'Canalização', subgrupoIds: ['s3', 's4'] },
    { id: 'g3', nome: 'Pinturas', subgrupoIds: ['s5', 's6'] },
    { id: 'g4', nome: 'Revestimentos', subgrupoIds: ['s7', 's8'] },
    { id: 'g5', nome: 'Eletricidade', subgrupoIds: ['s9', 's10'] },
    { id: 'g6', nome: 'Gesso cartonado', subgrupoIds: ['s11', 's12'] },
  ];

  const categorias: Categoria[] = [
    { id: 'c1', nome: 'Estrutura', grupoIds: ['g1'] },
    { id: 'c2', nome: 'Acabamentos', grupoIds: ['g3', 'g4', 'g6'] },
    { id: 'c3', nome: 'Instalações técnicas', grupoIds: ['g2', 'g5'] },
  ];

  const parceiros: Parceiro[] = [
    {
      id: 'p1',
      nome: 'Almeida & Filhos, Lda',
      tipos: ['Cliente'],
      nif: '502 341 887',
      email: 'geral@almeidafilhos.pt',
      telefone: '234 421 900',
      localidade: 'Aveiro',
    },
    {
      id: 'p2',
      nome: 'Betões do Mondego SA',
      tipos: ['Fornecedor'],
      nif: '505 118 402',
      email: 'encomendas@betoesmondego.pt',
      telefone: '239 700 114',
      localidade: 'Coimbra',
    },
    {
      id: 'p3',
      nome: 'Câmara Municipal de Ílhavo',
      tipos: ['Cliente'],
      nif: '506 778 351',
      email: 'obras@cm-ilhavo.pt',
      telefone: '234 329 600',
      localidade: 'Ílhavo',
    },
    {
      id: 'p4',
      nome: 'Tintas Norte, Lda',
      tipos: ['Fornecedor'],
      nif: '503 902 118',
      email: 'comercial@tintasnorte.pt',
      telefone: '229 380 447',
      localidade: 'Maia',
    },
    {
      id: 'p5',
      nome: 'Grupo Ferrão',
      tipos: ['Cliente', 'Fornecedor'],
      nif: '507 664 210',
      email: 'contacto@grupoferrao.pt',
      telefone: '253 610 088',
      localidade: 'Braga',
    },
    {
      id: 'p6',
      nome: 'Cerâmicas do Vouga SA',
      tipos: ['Fornecedor'],
      nif: '501 447 903',
      email: 'vendas@ceramicasvouga.pt',
      telefone: '234 910 220',
      localidade: 'Águeda',
    },
    {
      id: 'p7',
      nome: 'Condomínio Douro Vista',
      tipos: ['Cliente'],
      nif: '900 114 552',
      email: 'admin@dourovista.pt',
      telefone: '223 004 118',
      localidade: 'Vila Nova de Gaia',
    },
    {
      id: 'p8',
      nome: 'ElectroSul Instalações',
      tipos: ['Fornecedor', 'Cliente'],
      nif: '508 221 774',
      email: 'apoio@electrosul.pt',
      telefone: '289 445 100',
      localidade: 'Faro',
    },
  ];

  const catalogo: Artigo[] = [
    {
      id: 'i1',
      nome: 'Cimento Portland CEM II 42,5R 25 kg',
      categoriaId: 'c1',
      sku: 'CIM-425-25',
      codigoBarras: '5601234000117',
      ncm: '2523.29.00',
      unidade: 'saco',
      stock: 340,
      stockMin: 80,
      precoUnit: 6.35,
      markup: 22,
      custoMedio: 5.2,
      fornecedorId: 'p2',
      ativo: true,
      descricao:
        'Cimento comum para betões e argamassas correntes, conforme NP EN 197-1.',
      notas: 'Stock rotativo semanal. Confirmar validade em obra.',
      imagem: '',
    },
    {
      id: 'i2',
      nome: 'Areia lavada do rio',
      categoriaId: 'c1',
      sku: 'ARE-LAV-M3',
      codigoBarras: '5601234000124',
      ncm: '2505.10.00',
      unidade: 'm³',
      stock: 48,
      stockMin: 15,
      precoUnit: 27.9,
      markup: 18,
      custoMedio: 23.6,
      fornecedorId: 'p2',
      ativo: true,
      descricao: 'Areia siliciosa lavada, granulometria 0/4 mm.',
      notas: 'Entrega mínima de 6 m³.',
      imagem: '',
    },
    {
      id: 'i3',
      nome: 'Tubo PVC pressão 110 mm · 3 m',
      categoriaId: 'c3',
      sku: 'PVC-110-3',
      codigoBarras: '5601234000131',
      ncm: '3917.23.00',
      unidade: 'un',
      stock: 126,
      stockMin: 40,
      precoUnit: 18.4,
      markup: 25,
      custoMedio: 14.7,
      fornecedorId: 'p5',
      ativo: true,
      descricao: 'Tubo em PVC-U para redes de drenagem residual.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i4',
      nome: 'Torneira misturadora monocomando',
      categoriaId: 'c3',
      sku: 'TOR-MIS-01',
      codigoBarras: '5601234000148',
      ncm: '8481.80.11',
      unidade: 'un',
      stock: 62,
      stockMin: 20,
      precoUnit: 74.5,
      markup: 35,
      custoMedio: 55.2,
      fornecedorId: 'p5',
      ativo: true,
      descricao: 'Misturadora de bancada, acabamento cromado, classe de ruído I.',
      notas: 'Modelo em fim de linha — validar substituto.',
      imagem: '',
    },
    {
      id: 'i5',
      nome: 'Tinta plástica mate branca 15 L',
      categoriaId: 'c2',
      sku: 'TIN-PLM-15',
      codigoBarras: '5601234000155',
      ncm: '3209.10.00',
      unidade: 'balde',
      stock: 54,
      stockMin: 24,
      precoUnit: 62.8,
      markup: 28,
      custoMedio: 49.1,
      fornecedorId: 'p4',
      ativo: true,
      descricao: 'Tinta aquosa mate para interiores, rendimento 10 m²/L.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i6',
      nome: 'Primário fixador aquoso 5 L',
      categoriaId: 'c2',
      sku: 'PRI-FIX-05',
      codigoBarras: '5601234000162',
      ncm: '3209.10.00',
      unidade: 'balde',
      stock: 18,
      stockMin: 20,
      precoUnit: 31.2,
      markup: 30,
      custoMedio: 24.0,
      fornecedorId: 'p4',
      ativo: true,
      descricao: 'Primário de fixação para suportes absorventes.',
      notas: 'Abaixo do stock mínimo — repor.',
      imagem: '',
    },
    {
      id: 'i7',
      nome: 'Azulejo cerâmico 30×60 branco',
      categoriaId: 'c2',
      sku: 'AZU-3060-B',
      codigoBarras: '5601234000179',
      ncm: '6907.21.00',
      unidade: 'm²',
      stock: 410,
      stockMin: 120,
      precoUnit: 14.9,
      markup: 32,
      custoMedio: 11.3,
      fornecedorId: 'p6',
      ativo: true,
      descricao: 'Revestimento cerâmico retificado, acabamento brilhante.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i8',
      nome: 'Pavimento flutuante carvalho 8 mm',
      categoriaId: 'c2',
      sku: 'PAV-FLU-08',
      codigoBarras: '5601234000186',
      ncm: '4411.13.00',
      unidade: 'm²',
      stock: 233,
      stockMin: 90,
      precoUnit: 21.6,
      markup: 27,
      custoMedio: 17.0,
      fornecedorId: 'p6',
      ativo: true,
      descricao: 'Pavimento laminado AC4 com sistema de encaixe.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i9',
      nome: 'Cabo H07V-K 2,5 mm²',
      categoriaId: 'c3',
      sku: 'CAB-H07-25',
      codigoBarras: '5601234000193',
      ncm: '8544.49.00',
      unidade: 'm',
      stock: 1850,
      stockMin: 600,
      precoUnit: 0.94,
      markup: 40,
      custoMedio: 0.67,
      fornecedorId: 'p8',
      ativo: true,
      descricao: 'Condutor flexível isolado em PVC, 450/750 V.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i10',
      nome: 'Quadro elétrico 12 módulos',
      categoriaId: 'c3',
      sku: 'QUA-ELE-12',
      codigoBarras: '5601234000209',
      ncm: '8537.10.99',
      unidade: 'un',
      stock: 27,
      stockMin: 10,
      precoUnit: 48.7,
      markup: 34,
      custoMedio: 36.3,
      fornecedorId: 'p8',
      ativo: true,
      descricao: 'Quadro de embutir com porta opaca e barramento de terra.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i11',
      nome: 'Placa gesso cartonado 13 mm · 1200×2500',
      categoriaId: 'c2',
      sku: 'GES-PLA-13',
      codigoBarras: '5601234000216',
      ncm: '6809.11.00',
      unidade: 'un',
      stock: 214,
      stockMin: 60,
      precoUnit: 9.8,
      markup: 26,
      custoMedio: 7.75,
      fornecedorId: 'p5',
      ativo: true,
      descricao: 'Placa standard para divisórias e tetos falsos.',
      notas: '',
      imagem: '',
    },
    {
      id: 'i12',
      nome: 'Perfil metálico C48 · 3 m',
      categoriaId: 'c2',
      sku: 'GES-PER-C48',
      codigoBarras: '5601234000223',
      ncm: '7308.90.59',
      unidade: 'un',
      stock: 96,
      stockMin: 60,
      precoUnit: 4.55,
      markup: 24,
      custoMedio: 3.65,
      fornecedorId: 'p5',
      ativo: false,
      descricao: 'Perfil galvanizado para estrutura de gesso cartonado.',
      notas: 'Artigo suspenso até nova adjudicação.',
      imagem: '',
    },
  ];

  const agenda: Marcacao[] = [
    {
      id: 'a1',
      descricao: 'Vistoria de estrutura — Rua do Carmo, 14',
      estado: 'Em curso',
      inicioData: d(0),
      inicioHora: '09:00',
      fimData: d(0),
      fimHora: '11:00',
      detalhes:
        '<p>Confirmar <b>armaduras do piso 1</b> com o eng. Pires.</p><ul><li>Levar relatório de betonagem</li><li>Fotografar juntas</li></ul>',
    },
    {
      id: 'a2',
      descricao: 'Reunião de adjudicação — Grupo Ferrão',
      estado: 'Em espera',
      inicioData: d(0),
      inicioHora: '15:00',
      fimData: d(0),
      fimHora: '16:30',
      detalhes: '<p>Rever margens do orçamento <b>ORC-2026-014</b>.</p>',
    },
    {
      id: 'a3',
      descricao: 'Receção de betão — obra Ílhavo',
      estado: 'Concluído',
      inicioData: d(1),
      inicioHora: '08:00',
      fimData: d(1),
      fimHora: '09:00',
      detalhes: '<p>Guia de remessa arquivada.</p>',
    },
    {
      id: 'a4',
      descricao: 'Medição de revestimentos — Douro Vista',
      estado: 'Em revisão',
      inicioData: d(1),
      inicioHora: '14:00',
      fimData: d(1),
      fimHora: '17:00',
      detalhes: '',
    },
    {
      id: 'a5',
      descricao: 'Visita técnica ElectroSul',
      estado: 'Adiado',
      inicioData: d(2),
      inicioHora: '10:00',
      fimData: d(2),
      fimHora: '12:00',
      detalhes: '<p>Reagendar para a semana seguinte.</p>',
    },
    {
      id: 'a6',
      descricao: 'Fecho de contas de aprovisionamento',
      estado: 'Em espera',
      inicioData: d(3),
      inicioHora: '09:00',
      fimData: d(3),
      fimHora: '10:30',
      detalhes: '',
    },
    {
      id: 'a7',
      descricao: 'Entrega de azulejo — Cerâmicas do Vouga',
      estado: 'Em curso',
      inicioData: d(3),
      inicioHora: '13:00',
      fimData: d(3),
      fimHora: '14:00',
      detalhes: '',
    },
    {
      id: 'a8',
      descricao: 'Auditoria de segurança em estaleiro',
      estado: 'Em espera',
      inicioData: d(4),
      inicioHora: '11:00',
      fimData: d(4),
      fimHora: '13:00',
      detalhes: '<p>Checklist CSS obrigatória.</p>',
    },
    {
      id: 'a9',
      descricao: 'Apresentação de orçamento — CM Ílhavo',
      estado: 'Em espera',
      inicioData: d(7),
      inicioHora: '10:00',
      fimData: d(7),
      fimHora: '11:00',
      detalhes: '',
    },
    {
      id: 'a10',
      descricao: 'Levantamento em Gaia — pintura de fachada',
      estado: 'Cancelado',
      inicioData: d(8),
      inicioHora: '16:00',
      fimData: d(8),
      fimHora: '18:00',
      detalhes: '',
    },
  ];

  const orcamentos: Orcamento[] = [
    {
      id: 'o1',
      ref: 'ORC-2026-012',
      clienteId: 'p1',
      obra: 'Reabilitação Rua do Carmo, 14',
      dataEmissao: iso(addDays(today, -12)),
      dataValidade: iso(addDays(today, 18)),
      estado: 'Em revisão',
      ambientes: [
        {
          id: 'e1',
          nome: 'Sala comum',
          linhas: [
            { id: 'l1', itemId: 'i7', qtd: 42.5, preco: 14.9, nota: 'Rodapé incluído' },
            { id: 'l2', itemId: 'i5', qtd: 3, preco: 62.8, nota: '' },
            { id: 'l3', itemId: 'i11', qtd: 26, preco: 9.8, nota: 'Teto falso' },
          ],
        },
        {
          id: 'e2',
          nome: 'Cozinha',
          linhas: [
            { id: 'l4', itemId: 'i7', qtd: 18.75, preco: 14.9, nota: '' },
            { id: 'l5', itemId: 'i4', qtd: 2, preco: 74.5, nota: 'Bancada e lava-loiça' },
          ],
        },
      ],
    },
    {
      id: 'o2',
      ref: 'ORC-2026-014',
      clienteId: 'p5',
      obra: 'Ampliação armazém Braga',
      dataEmissao: iso(addDays(today, -4)),
      dataValidade: iso(addDays(today, 26)),
      estado: 'Em espera',
      ambientes: [
        {
          id: 'e3',
          nome: 'Nave principal',
          linhas: [
            { id: 'l6', itemId: 'i1', qtd: 120, preco: 6.35, nota: '' },
            { id: 'l7', itemId: 'i2', qtd: 8.5, preco: 27.9, nota: 'Entrega fracionada' },
            { id: 'l8', itemId: 'i9', qtd: 420, preco: 0.94, nota: '' },
          ],
        },
      ],
    },
    {
      id: 'o3',
      ref: 'ORC-2026-015',
      clienteId: 'p7',
      obra: 'Pintura de fachada — Douro Vista',
      dataEmissao: iso(addDays(today, -1)),
      dataValidade: iso(addDays(today, 29)),
      estado: 'Em espera',
      ambientes: [
        {
          id: 'e4',
          nome: 'Fachada norte',
          linhas: [
            { id: 'l9', itemId: 'i5', qtd: 12, preco: 62.8, nota: '' },
            { id: 'l10', itemId: 'i6', qtd: 9, preco: 31.2, nota: 'Duas demãos' },
          ],
        },
        {
          id: 'e5',
          nome: 'Caixa de escadas',
          linhas: [{ id: 'l11', itemId: 'i5', qtd: 4, preco: 62.8, nota: '' }],
        },
      ],
    },
  ];

  return { subgrupos, grupos, categorias, parceiros, catalogo, agenda, orcamentos };
}
